### ISSUE TITLE
Perform OCR with Azure Document Intelligence 📃🧠

### ISSUE THREAD

**Issue by Nalito** [mlsanigeria/speak-to-docs#10]
# Perform OCR with Azure Document Intelligence 📃🧠

## What is Needed
Contributors are needed to implement an Azure Document Intelligence Solution to optimally extract contents of documents uploaded by the users. To get started with Azure Document Intelligence, you can follow the link here - [Introduction to Azure AI Document Intelligence](https://learn.microsoft.com/en-us/training/modules/intro-to-form-recognizer/?wt.mc_id=studentamb_217190).

## How to Contribute

- Get familiar with the scripts and documentations already provided in the [repository](https://github.com/mlsanigeria/speak-to-docs).
- Test your code: It is pertinent that you check your code runs smoothly before making a pull request.
- Create a Pull Request: Submit a pull request to the repository with your code in the appropriate script and include any necessary documentation.

## Getting Started
Before you begin, ensure you have read the [Contribution Guidelines](https://github.com/mlsanigeria/speak-to-docs/blob/9240693ec9a595a1b52fbd69aa187ea545eae65d/CONTRIBUTING.md) in the repository

We are excited to see your contributions! Happy Hacking! 🎉

**Comment by Coding-Turtle0** [comment]
Greetings!!
I saw this issue open...can you kindly mention in which format do I need to store the text(Eg:- .json or word or csv ) after performing OCR with Azure Document Intelligence....and it would be great if you assign me this issue. I would like to contribute to it.

**Comment by Sammybams** [comment]
> Greetings!! I saw this issue open...can you kindly mention in which format do I need to store the text(Eg:- .json or word or csv ) after performing OCR with Azure Document Intelligence....and it would be great if you assign me this issue. I would like to contribute to it.

Hello @Coding-Turtle0, thank you very much for your interest. This issue has actually been solved by another contributor and should have been closed. You can check it out at  #23. And would be extracted to as txt. You can go ahead to implement to Langchain DocInMemory embedding for these files if you wish. Thank you very much for your interest.
