### ISSUE TITLE
Streamlit Interface: Error Handling 📃☁️

### ISSUE THREAD

**Issue by Nalito** [mlsanigeria/speak-to-docs#11]
# Streamlit Interface: Error Handling 📃☁️

## What is Needed
Contributors are expected to optimize the Streamlit User Interface so that the users are provided with clear error messages during document uploads. Users may incorrectly upload more than the file limit, record poor quality voice notes or upload more than two documents. Clear error messages should be displayed explaining errors to the user. 

## How to Contribute

- Get familiar with the scripts and documentation already provided in the [repository](https://github.com/mlsanigeria/speak-to-docs).
- Test your code: It is pertinent that you check your code runs smoothly before making a pull request.
- Create a Pull Request: Submit a pull request to the repository with your code in the appropriate script and include any necessary documentation.

## Getting Started
Before you begin, ensure you have read the [Contribution Guidelines](https://github.com/mlsanigeria/speak-to-docs/blob/main/CONTRIBUTING.md) in the repository

We are excited to see your contributions! Happy Hacking! 🎉

**Comment by SalmanDeveloperz** [comment]
Hi,

I noticed that the CONTRIBUTING.md file is currently empty. Could you kindly update it? Additionally, could you explain where changes should be made?
Thank you!

**Comment by Sammybams** [comment]
> Hi,
> 
> I noticed that the CONTRIBUTING.md file is currently empty. Could you kindly update it? Additionally, could you explain where changes should be made? Thank you!

Sincere apologies for that. Thank you @SalmanDeveloperz. The link referenced in this issue was to a much older commit that didn't have it populated as at then. It has now been updated. Thank you very much for bringing it to our attention.
