### ISSUE TITLE
Document Uploads 📝- Large Document Processing 

### ISSUE THREAD

**Issue by Odeyiany2** [mlsanigeria/speak-to-docs#12]
### **Project Overview**
For optimization, there is need to boost the file processing experience by setting a limit on the size of documents uploaded. To avoid delays in response, we need to enforce a page limit on uploaded documents.

### **What is Needed**
Contributors are required to implement a check that ensures documents uploaded have a page limit of 50. This will help mitigate delays when processing large files.

### **How to Contribute**
1. Get familiar with the scripts and documentations already provided in the [repository](https://github.com/mlsanigeria/speak-to-docs).
2. Implement the Page Limit: Modify the file upload logic to ensure documents with more than 50 pages are rejected or flagged.
3. Test your code: Ensure your solution works smoothly before submitting. 
4. Create a Pull Request: Submit a pull request to the repository with your code in the appropriate script and include any necessary documentation.

### **Getting Started**
Before you begin, ensure you have read the [Contribution Guidelines](https://github.com/mlsanigeria/speak-to-docs/blob/9240693ec9a595a1b52fbd69aa187ea545eae65d/CONTRIBUTING.md) in the repository

Looking forward to your solutions! Happy Hacking! 🎉

**Comment by KeneNwogu** [comment]
hello, please could I get assigned to this?

**Comment by Sammybams** [comment]
> hello, please could I get assigned to this?

Yes @KeneNwogu, you can go ahead and work on this.
