### ISSUE TITLE
Implement Speech Synthesis with Azure AI Speech Service 💬🗣

### ISSUE THREAD

**Issue by Odeyiany2** [mlsanigeria/speak-to-docs#19]
### **What is Needed**
Contributors are needed to implement a speech synthesis (text-to-speech) function using Azure AI Speech Service. Work to fine-tune the existing [speech_io.py](https://github.com/mlsanigeria/speak-to-docs/blob/main/src/speech_io.py) script. Also check out the resources at the end of the [Contribution Guidelines](https://github.com/mlsanigeria/speak-to-docs/blob/9240693ec9a595a1b52fbd69aa187ea545eae65d/CONTRIBUTING.md) to learn how to use the speech synthesis API.

### **How to Contribute**
1. Get familiar with the scripts and documentations already provided in the [repository](https://github.com/mlsanigeria/speak-to-docs).
2. Test your code: It is pertinent that you check your code runs smoothly before making a pull request.
3. Create a Pull Request: Submit a pull request to the repository with your code in the appropriate script and include any necessary documentation.

### **Getting Started**
Before you begin, ensure you have read the [Contribution Guidelines](https://github.com/mlsanigeria/speak-to-docs/blob/9240693ec9a595a1b52fbd69aa187ea545eae65d/CONTRIBUTING.md) in the repository

We are excited to see your contributions! Happy Hacking! 🎉

**Comment by KeneNwogu** [comment]
Can I get assigned to this? I'll integrate it into the streamlit script

**Comment by Sammybams** [comment]
> Can I get assigned to this? I'll integrate it into the streamlit script

Thank you @KeneNwogu. You can go ahead to work on this issue. The speech synthesis has already been implemented in the `speech_io.py` script. So all that's needed is the integration to the chat interface of Streamlit which you can work on. Please when making your PR on this, include a video snippet/screenshot of your tests and how it looks in the Streamlit UI. Thank you very much.

**Comment by KeneNwogu** [comment]
Thank you very much. I'm on it
