### ISSUE TITLE
RAG Implementation: Document Retrieval 🚀

### ISSUE THREAD

**Issue by Odeyiany2** [mlsanigeria/speak-to-docs#2]
### **Project Overview** 
For this project we are looking at creating a RAG solution leveraging the power of Microsoft Azure that takes in documents from users and allow user to query the documents through a voice message. 

### **What is Needed**
We need contributors to implement a proper and efficient chunking strategy for the documents uploaded by user so as to ensure that the most relevant section of the document is retrieved to answer queries.
- Consider breaking the documents into smaller, semantically meaningful chunks for optimal retrieval.
- The solution should scale efficiently and work with the suggested document types (PDFs, TXT files).

### **How to Contribute**
1. Get familiar with the starter scripts and documentations already provided in the [repository](https://github.com/mlsanigeria/speak-to-docs).
2. **Test your code:** It is pertinent that you check your code runs smoothly before making a pull request. 
3. **Create a Pull Request:** Submit a pull request to the repository with your code in the appropriate script and include any necessary documentation

### **Getting Started**
Ensure to properly read through the [Contribution Guidelines](https://github.com/mlsanigeria/speak-to-docs/blob/9240693ec9a595a1b52fbd69aa187ea545eae65d/CONTRIBUTING.md) to get started.

We are looking forward to your contributions. Happy Hacking! 🎉

**Comment by mohammedfirdouss** [comment]
@Odeyiany2 Can I work on this issue?

**Comment by Odeyiany2** [comment]
Hello @Firdous2307, yes you can. Please ensure to properly check the available scripts and read through the contribution guidelines. We are looking forward to your contribution!

**Comment by mohammedfirdouss** [comment]
@Odeyiany2 no problem at all. Can I be assigned to this issue?

**Comment by Sammybams** [comment]
> @Odeyiany2 no problem at all. Can I be assigned to this issue?

You can go ahead to work on it @Firdous2307. We keep the issues open to everyone to pick up.
