### ISSUE TITLE
LangChain DocArrayInMemorySearch as Vector Store Implementation 📄

### ISSUE THREAD

**Issue by Odeyiany2** [mlsanigeria/speak-to-docs#29]
**What is Needed**
Contributors are needed to implement LangChain `DocArrayInMemorySearch` as a vector store. Fine-tune the [streamlit script](https://github.com/mlsanigeria/speak-to-docs/blob/main/main.py) to reflect this feature. Also ensure that document memory is cached per session, enabling the app to retain uploaded documents and queries during individual user sessions.

**How to Contribute**
1. Get familiar with the scripts and documentation already provided in the [repository](https://github.com/mlsanigeria/speak-to-docs).
2. Test your code: It is pertinent that you check your code runs smoothly before making a pull request.
3. Create a Pull Request: Submit a pull request to the repository with your code in the appropriate script and include any necessary 
documentation.

**Getting Started**
Before you begin, ensure you have read the [Contribution Guidelines](https://github.com/mlsanigeria/speak-to-docs/blob/9240693ec9a595a1b52fbd69aa187ea545eae65d/CONTRIBUTING.md) in the repository

We are excited to see your contributions! Happy Hacking! 🎉

**Comment by hrit2773** [comment]
@Odeyiany2 can you assign this to me I wanna work on this.

**Comment by Sammybams** [comment]
> @Odeyiany2 can you assign this to me I wanna work on this.

You can go ahead to work on this @hrit2773. We are keeping the issue open to whoever wishes to implement it.
