### ISSUE TITLE
Streamlit Interface: Speech Synthesis Integration

### ISSUE THREAD

**Issue by Odeyiany2** [mlsanigeria/speak-to-docs#35]
**What is Needed**
Contributors should modify the [main.py file](https://github.com/mlsanigeria/speak-to-docs/blob/main/main.py) and implement a feature that ensures that speech synthesis should be triggered only when the user clicks a "Play" option to hear the response. 
* By default, even if a user sends an audio recording of a query, the response should be returned as text output.
* Just like the audio input is optional (users can either send text or audio), the speech synthesis should also be optional. Users should be able to read the text response by default then they can decide to click the "Play" button, which should be implemented on the left pane, under the Document upload section, to hear the audio response.

**How to Contribute**
1. Get familiar with the scripts and documentation already provided in the [repository](https://github.com/mlsanigeria/speak-to-docs).
2. Test your code: It is pertinent that you check your code runs smoothly before making a pull request.
3. Create a Pull Request: Submit a pull request to the repository with your code in the appropriate script and include any necessary documentation.

**Getting Started**
Before you begin, ensure you have read the [Contribution Guidelines](https://github.com/mlsanigeria/speak-to-docs/blob/9240693ec9a595a1b52fbd69aa187ea545eae65d/CONTRIBUTING.md) in the repository

We are excited to see your contributions! Happy Hacking! 🎉

**Comment by Sammybams** [comment]
Check this out @KeneNwogu.

**Comment by KeneNwogu** [comment]
I'll work on it. Thanks sm for the tag! @Sammybams
