### ISSUE TITLE
RAG Implementation: Efficient Memory Storage 🧠

### ISSUE THREAD

**Issue by Odeyiany2** [mlsanigeria/speak-to-docs#4]
### **What is Needed**
Contributors are needed to implement an efficient memory storage that will help to optimally tracks conversation history, even in scenarios involving multiple file uploads. Maintaining proper session state management. Session timeouts are an option. 

### **How to Contribute**
1. Get familiar with the scripts and documentations already provided in the [repository](https://github.com/mlsanigeria/speak-to-docs). 
2. **Test your code:** It is pertinent that you check your code runs smoothly before making a pull request.
3. **Create a Pull Request:** Submit a pull request to the repository with your code in the appropriate script and include any necessary documentation. 

### **Getting Started**
Before you begin, ensure you have read the [Contribution Guidelines](https://github.com/mlsanigeria/speak-to-docs/blob/9240693ec9a595a1b52fbd69aa187ea545eae65d/CONTRIBUTING.md) in the repository

We are excited to see your contributions! Happy Hacking! 🎉

**Comment by mohammedfirdouss** [comment]
@Odeyiany2 I would like to work on this
