### ISSUE TITLE
RAG Implementation: Multiple File Uploads

### ISSUE THREAD

**Issue by Nalito** [mlsanigeria/speak-to-docs#7]
# RAG Implementation: Multiple File Uploads 📃📃

## What is Needed
Contributors are needed to implement a module that supports at most 2 document uploads from users. This will ensure that the system can manage and prioritize responses from different documents. 

## How to Contribute
- Get familiar with the scripts and documentations already provided in the [repository](https://github.com/mlsanigeria/speak-to-docs).
- Test your code: It is pertinent that you check your code runs smoothly before making a pull request.
- Create a Pull Request: Submit a pull request to the repository with your code in the appropriate script and include any necessary documentation.

## Getting Started
Before you begin, ensure you have read the [Contribution Guidelines](https://github.com/mlsanigeria/speak-to-docs/blob/9240693ec9a595a1b52fbd69aa187ea545eae65d/CONTRIBUTING.md) in the repository

We are excited to see your contributions! Happy Hacking! 🎉

**Comment by mohammedfirdouss** [comment]
@Nalito Can I work on this issue?

**Comment by MbuviM** [comment]
Add me to this kindly.

**Comment by Sammybams** [comment]
> Add me to this kindly.

Apologies, please.  This issue has already been solved and should have been closed. Thank you
