### ISSUE TITLE
File Compatibility - Document Uploads 📝

### ISSUE THREAD

**Issue by Odeyiany2** [mlsanigeria/speak-to-docs#9]
### **Project Overview**
We are building a solution that processes user-uploaded files, and we need to ensure compatibility with specific file types.

### **What is Needed**
Contributors are needed to implement a file compatibility check. Modify the existing code to accept files of a certain type from users. Major file types are: PDFs, TXTs and PPTX

### **How to Contribute**
1. Get familiar with the scripts and documentations already provided in the [repository](https://github.com/mlsanigeria/speak-to-docs).
2. Test your code: It is pertinent that you check your code runs smoothly before making a pull request.
3. Create a Pull Request: Submit a pull request to the repository with your code in the appropriate script and include any necessary documentation.

### **Getting Started**
Before you begin, ensure you have read the [Contribution Guidelines](https://github.com/mlsanigeria/speak-to-docs/blob/9240693ec9a595a1b52fbd69aa187ea545eae65d/CONTRIBUTING.md) in the repository

Looking forward to what you can do! Happy Hacking! 🎉

**Comment by mutant138** [comment]
Kindly assign this to me.

**Comment by Sammybams** [comment]
> Kindly assign this to me.

You can go ahead to work on it @mutant138.
